// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bento: dynamic(() => import("./Bento")),
  call_to_action: dynamic(() => import("./CallToAction")),
  case_studies: dynamic(() => import("./CaseStudies")),
  heros: dynamic(() => import("./Heros")),
  integrations: dynamic(() => import("./Integrations")),
  rich_text: dynamic(() => import("./RichText")),
  showcase: dynamic(() => import("./Showcase")),
};
